# All config specified here exists to override their default value.
# Untouched default configs are removed and should refer to the docs:
# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://seorang.dev"

title = "Hizzely"
description = "Description"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
